version: "3"

networks:
        gitea:
                external: false

services:
        server:
                image: gitea/gitea:1.14.2
                container_name: gitea
                environment: 
                        - ER_UID=1000
                        - USER_GID=1000
                        - GITEA__database__DB_TYPE=mysql
                        - GITEA__database__HOST=db:3306
                        - GITEA__database__NAME=gitea
                        - GITEA__database__USER=gitea
                        - GITEA__database__PASSWD=gitea
                restart: always
                networks:
                        - gitea
                volumes:
                        - ./gitea:/data
                        - /etx/timezone:/etc/timezone:ro
                        - /etc/localtime:/etc/localtime:ro
                ports:
                        - "80:3000"
                        - "222:22"
                depends_on:
                        - db
        db:
                image: mysql:8
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=gitea
                        - MYSQL_USER=gitea
                        - MYSQL_PASSWORD=gitea
                        - MYSQL_DATABASE=gitea
                networks:
                        - gitea
                volumes:
                        - ./mysql:/var/lib/mysql
        drone:
                image: drone/drone:2.0.1
                restart: always
                volumes:
                        - ./drone:/var/lib/drone
                ports:
                        - "81:80"
                environment:
                        - DRONE_SERVER_HOST=192.168.0.60:81
                        - DRONE_SERVER_PROTO=http
                        - DRONE_RPC_SECRET=108e640bbc86cac3be5d86d122
                        - DRONE_GITEA_CLIENT_SECRET=xHpdAFmaK4aEXUFNTpzCpaKa5vivyAE5QsetcW_LBlw=
                        - DRONE_GITEA_SERVER=http://192.168.0.60:80
                        - DRONE_GITEA_CLIENT_ID=20ca86f0-8f1f-4535-abdd-4a0a53137413
                        - DRONE_USER_CREATE=username:user123,admin:true 
        drone-agent:
                image: drone/drone-runner-docker:1.6.3
                restart: always
                depends_on:
                        - drone
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                environment:
                        - DRONE_RPC_HOST=drone:80
                        - DRONE_RPC_PROTO=http
                        - DRONE_RPC_SECRET=108e640bbc86cac3be5d86d122 
                                        



